version: 2
jobs:
  build:
    docker:
      - image: debian
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            apt update
            apt install -y \
              devscripts libsystemd-dev gcc python3-dev pkg-config \
              iptables devscripts ruby2.3-dev rubygems build-essential:native \
              python3-setuptools python3-all python3-pkg-resources python3-iptables python3-psutil \
              python3-certifi python3-cffi python3-chardet  python3-cryptography python3-idna python3-netifaces \
              python3-psutil python3-openssl  python3-iptables python3-tz python3-requests python3-sh python3-systemd \
              python3-venv python3-pip
            pip3 install -r requirements-dev.txt
      - run:
          name: Run linting and metrics
          command: |
            flake8 ./ --exclude=venv --ignore=E501 --output-file test-reports
      - run:
          name: Run tests
          command: |
            pytest --cov=agent
      - run:
          name: Build dpkg packages
          command: |
            debuild  -i -us -uc -b
            mkdir -p /tmp/deb
            mv ../*.deb /tmp/deb
      - deploy:
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                gem install rake package_cloud
                package_cloud push wott/agent/debian/stretch /tmp/deb/*.deb
                package_cloud push wott/agent/raspbian/stretch /tmp/deb/*.deb
              fi
      - store_artifacts:
          path: test-reports
          destination: test-reports
      - store_artifacts:
          path: /tmp/deb
