version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8-jessie
    steps:
      - checkout
      - run:
          name: Install iptables
          command: |
            sudo apt-get install -y iptables
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
      - run:
          name: Install nmap
          command: |
            sudo apt-get install -y nmap
      - run:
          name: run linting and metrics
          command: |
            . venv/bin/activate
            flake8 ./ --exclude=venv --ignore=E501 --output-file test-reports
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --cov=agent
      - store_artifacts:
          path: test-reports
          destination: test-reports
