version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8-stretch
    steps:
      - checkout
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install -y \
              nmap iptables devscripts ruby2.3-dev rubygems \
              build-essential:native python-setuptools python3-all python3-setuptools
      - run:
          name: Install PackageCloud
          command: |
            sudo gem install rake package_cloud
      - run:
          name: run linting and metrics
          command: |
            . venv/bin/activate
            flake8 ./ --exclude=venv --ignore=E501 --output-file test-reports
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --cov=agent
      - run:
          name: build DEB package
          command: |
            debuild  -i -us -uc -b
            mkdir -p /tmp/deb
            mv ../*.deb /tmp/deb
      - deploy:
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                package_cloud push wott/agent/debian/stretch /tmp/deb/*.deb
                package_cloud push wott/agent/raspbian/stretch /tmp/deb/*.deb
              fi
      - store_artifacts:
          path: test-reports
          destination: test-reports
      - store_artifacts:
          path: /tmp/deb
